name = "json-saver"
main = "src/worker.mjs"
compatibility_date = "2024-11-01"

[vars]
REPO_OWNER = "Hades1225-design"
REPO_NAME  = "HadesEidolon"          # ← 這裡改成目標專案
REPO_BRANCH = "main"

# 正式上線，限制成你的 Pages 網域（建議用完整來源）
ALLOWED_ORIGIN = "https://hades1225-design.github.io"
