name = "hades-json-writer"
main = "worker.js"
compatibility_date = "2024-12-01"

[vars]
GH_OWNER  = "Hades1225-design"
GH_REPO   = "HadesEidolon"
GH_BRANCH = "main"
# 多個來源用逗號隔開（GitHub Pages + 你的測試域）
ALLOWED_ORIGIN = "https://hades1225-design.github.io"

# 機密用 secret
# wrangler secret put GH_TOKEN
